# --- Required options --- #
title: Guillem Fernández Arrondo
author: Guillem Fernández Arrondo

# --- List of links in the navigation bar --- #
navbar-links:
  Inicio: "/"
  Proyectos: "/proyectos"
  Sobre mí: "/sobre-mi"

# --- Logo --- #
# Sube tu foto a /assets/img/ y actualiza esta línea
avatar: "/assets/img/avatar.jpg"
round-avatar: true

# --- Footer social media links --- #
social-network-links:
  email: "guillemfernandezz@gmail.com"
  github: guillemfernandezz
  linkedin: Guillem Fernandez Arrondo # (Asegúrate que esto es tu "usuario" de LinkedIn, no tu nombre)

# --- General options --- #
share-links-active:
  linkedin: true
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: false # Lo ponemos en false, no es un blog
edit_page_button: true

# --- SEO Keywords --- #
keywords: "Guillem Fernández, GIS, Teledetección, Geomática, QGIS, Python, Geo-IT, Analista GIS, Barcelona, UPC, Incendios Forestales"

# --- Colours / background image --- #
# (Dejamos los colores por defecto por ahora)
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# --- Web Analytics Section --- #
# (Lo veremos más adelante, pero lo dejamos listo)
# gtag: "G-XXXXXXXXXX"

# --- Misc --- #
date_format: "%B %-d, %Y"

# --- Jekyll Options --- #
timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Cargar nuestro archivo de estilos
site-css:
  - "assets/css/css/custom.css"
